title: jtwenty app documentation
description: Documentation of the jtwenty app
theme: just-the-docs

url: https://rauf-dev.github.io/jtwenty-docs/

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/logo-large.svg"
