title: jtwenty app documentation
description: Documentation of the jtwenty app
theme: just-the-docs

url: https://rauf-dev.github.io/jtwenty-docs/

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/logo-large.svg"

# Aux links for the upper right navigation
aux_links:
  "jtwenty on GitHub" 
    - "//github.com/rauf-dev/jwenty"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

# Comitted

# Mermaid diagram integration
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.2.3"

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

